name: auto add client libs

on:
  #schedule:
  #  - cron: '30 5 * * *'
  push:
  pull_request:
  workflow_dispatch:
    inputs:

jobs:
  add-client-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: KittyCAD/ts-actions/autogen-readme-list@v0.3.0
        id: update-readme
        with:
          github-token: ${{ secrets.GLOBAL_PAT }}
          path: './profile/README.md'

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --ignore-submodules --quiet HEAD --; then echo "false"; else echo "true"; fi)
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.git-check.outputs.modified == 'true'
        with:
          commit_message: "🔨 DRAGON THOSE PUBLIC CLIENTS AND ACTIONS ⚙️"
          commit_options: '-s'
          file_pattern: profile/README.md
